### ISSUE TITLE
use  calendar  

### ISSUE THREAD

**Issue by winterwolf45** [mer30hamid/PersianBoard#1]
hi is it possible use PersianBoard  without change language kanboard to persian  ?

**Comment by mer30hamid** [comment]
Hi, just comment (or remove) line 12 and 18 in this file:

https://github.com/mer30hamid/PersianBoard/blob/master/Plugin.php

**Comment by winterwolf45** [comment]
hi thank you for answer 
but again don't work after comment 
and if i change language to persian it can work

**Comment by mer30hamid** [comment]
I tested it and it works, if you want disable force RTL, comment out line 13 too,
Inside the file "Plugin.php":
A: comment (or remove) line 12 and 18
B: if you want disable force RTL, comment out line 13
![image](https://user-images.githubusercontent.com/1561497/116506635-e8f68280-a8d2-11eb-878d-d8e5cb14e426.png)

**Comment by winterwolf45** [comment]
really thank you for spent time 
it's work 
and container need it restart after reset it's work 
thank you
