### ISSUE TITLE
مشکل درج نشدن در دیتابیس

### ISSUE THREAD

**Issue by rezakhsh** [mer30hamid/PersianBoard#2]
سلام دوست من ممنون بابات این پلاگین ولی بعد از تغییر دادن زمان و بعد از فشردن دکمه ذخیره زمان در دیتابیس ذخیره نمیشود و همان زمان دیفالت قبلی را نمایش میدهد

**Comment by mer30hamid** [comment]
سلام، خواهش می کنم، اگر امکانش هست تصویر قسمتی که این مشکل رو داره بگذارید

**Comment by rezakhsh** [comment]
![5fc75715-e0c1-4953-b7d4-1fa733bcb631](https://github.com/mer30hamid/PersianBoard/assets/50210179/519f2070-86db-4394-9895-5ab01ba7bd9b)
ببین تو این عکس من تغییر میدم ولی وقتی دکمه ذخیره رو میزنم تغییر اعما نمیشه و همون تاریخ پیشفرض رو نشون میده 
![391d592d-46a7-4c1e-b3f0-dfe289a54595](https://github.com/mer30hamid/PersianBoard/assets/50210179/d9a81d12-1ddb-458a-b035-e6eee1e1a574)

**Comment by mer30hamid** [comment]
> ![5fc75715-e0c1-4953-b7d4-1fa733bcb631](https://private-user-images.githubusercontent.com/50210179/342104973-519f2070-86db-4394-9895-5ab01ba7bd9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTgxODUsIm5iZiI6MTcxOTI5Nzg4NSwicGF0aCI6Ii81MDIxMDE3OS8zNDIxMDQ5NzMtNTE5ZjIwNzAtODZkYi00Mzk0LTk4OTUtNWFiMDFiYTdiZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2NDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Y2E3MzVkZDAwM2Q5OGVjZWQwNjExMDA5MmU2OTQ4ZTE5OGRlNDVhODZlY2I3MzkxNWNiMzQ2ZGVjNTljYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uf1EA3hERgL6_VbjplDlnFCdh1-u9Us2YOoP3Rxen3Q) ببین تو این عکس من تغییر میدم ولی وقتی دکمه ذخیره رو میزنم تغییر اعما نمیشه و همون تاریخ پیشفرض رو نشون میده ![391d592d-46a7-4c1e-b3f0-dfe289a54595](https://private-user-images.githubusercontent.com/50210179/342105087-d9a81d12-1ddb-458a-b035-e6eee1e1a574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTgxODUsIm5iZiI6MTcxOTI5Nzg4NSwicGF0aCI6Ii81MDIxMDE3OS8zNDIxMDUwODctZDlhODFkMTItMWRkYi00NThhLWIwMzUtZTZlZWUxZTFhNTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2NDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMGZjZGZiZjIwMjY1ZGJiMDRjZDcyNDI4Yzk4MDNkZmYxN2NlZjY2M2E5ZmU5MTA1MTEzOTZmNDdmY2ViNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MNmCVEooee6u4q9QdQ-XRcczEKdvBqBT5Sy7BUig-Kw)

همانطور که در تصویر اول مشخص هست، فرمت تاریخ انتخاب شده در مسیر :
تنظیمات > تنظیمات برنامه باید بصورت:
```
Y/m/d
```
انتخاب بشه در حالی که شما 
```
Y-m-d
```
رو انتخاب کردین، توی تصویر زیر نشون دادم:

![image](https://github.com/mer30hamid/PersianBoard/assets/1561497/b7699153-379a-40f7-93e8-a561ff02c7f7)

**Comment by rezakhsh** [comment]
ممنونم درست شد

**Comment by rezakhsh** [comment]
> ![5fc75715-e0c1-4953-b7d4-1fa733bcb631](https://private-user-images.githubusercontent.com/50210179/342104973-519f2070-86db-4394-9895-5ab01ba7bd9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTMwMTQsIm5iZiI6MTcxOTMxMjcxNCwicGF0aCI6Ii81MDIxMDE3OS8zNDIxMDQ5NzMtNTE5ZjIwNzAtODZkYi00Mzk0LTk4OTUtNWFiMDFiYTdiZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEwNTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYmY5YTQzOWYxOTc2MGU0OTlhZDViODQ4MTBmYWQxNDYwZDEwZDBiMzQ1MGIwZTUyM2NmYjVhZDhlNjk5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01V-MZ0WJpOogTYogF8cmHFi-7hhZ1B-G4IZdX6uy0s) ببین تو این عکس من تغییر میدم ولی وقتی دکمه ذخیره رو میزنم تغییر اعما نمیشه و همون تاریخ پیشفرض رو نشون میده ![391d592d-46a7-4c1e-b3f0-dfe289a54595](https://private-user-images.githubusercontent.com/50210179/342105087-d9a81d12-1ddb-458a-b035-e6eee1e1a574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTMwMTQsIm5iZiI6MTcxOTMxMjcxNCwicGF0aCI6Ii81MDIxMDE3OS8zNDIxMDUwODctZDlhODFkMTItMWRkYi00NThhLWIwMzUtZTZlZWUxZTFhNTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEwNTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MTNkNmRhMGNhYjdmNGQ5MWQyNDQ1MzExYmE0MTBlNWI5MGNkMGExZjgzMDM0YWJlOGE2NDQ0ODcyZmIyMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V8wZn2RbI_Ab1x8qqoWi_X9C2eZpedCKKp7zGJ_GepE)

درست شد

**Comment by mer30hamid** [comment]
> ممنونم درست شد

خواهش می کنم، یه تغییراتی دادم و نسخه جدید رو می تونید بصورت دستی از قسمت releases نصب کنید:

https://github.com/mer30hamid/PersianBoard/releases

البته امیدوارم بزودی در لیست مخزن پلاگین های نرم افزار هم بروز بشه
